### ISSUE TITLE
Angular State Inspector no longer works in Microsoft Edge (Chome) v92

### ISSUE THREAD

**Issue by thaoula** [anton-lunev/angular-state-inspector#16]
Hi,

Firstly, thanks so much for your awesome extension.

Your extension no longer seems to work in Microsoft Edge and displays blank -

![image](https://user-images.githubusercontent.com/349133/118353361-10667400-b590-11eb-8822-7a19a34232fc.png)

The same page in Chrome -

![image](https://user-images.githubusercontent.com/349133/118353384-270ccb00-b590-11eb-91b1-d187846a0476.png)

In previous versions of Edge or your extension we were able view the state of a component using your extenson.

Regards,
Tarek

**Comment by anton-lunev** [comment]
Hi @thaoula, thank you for the feedback.
I've just checked the extension on the latest edge(91.0.864.59) and it works as expected.
This might be a temporal bug in particular edge version, I saw similar bug in chrome canary.
Unfortunately there is nothing I can do until it's reproducible.
Sorry for inconvenience.

**Comment by maleet** [comment]
As now the latest edge is v92 and it is repoducible. 

Thanks for awesome extension. I use it all the time :)

**Comment by MLefebvreICO** [comment]
@anton-lunev It is indeed broken in Edge/Chrome v92.

Frankly, closing your eyes because the version of the browser was not the current release to me it's like saying "I don't care if it doesn't work in the future, I'll check this out when we'll be there". So now that's is released, everybody will have the issue 😐 

But unfortunately that doesn't seem to be an issue with this extension in particular, because every similar extension is broken 😢

**Comment by MLefebvreICO** [comment]
Probably caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1232063

**Comment by anton-lunev** [comment]
@MLefebvreICO Thanks for pointing to the root cause.
