### ISSUE TITLE
Feature: Edit State Data

### ISSUE THREAD

**Issue by beeing** [anton-lunev/angular-state-inspector#18]
Hi @anton-lunev, just wondering if editing the variable is possible which was what Angular Dev Tools capable of doing.

**Comment by anton-lunev** [comment]
Hi @beeing Chrome used to allow to do that, however it seems this feature was removed. I'm talking about chrome because extension uses default chrome object rendering like you would print in devtools console.

What you can do is to edit state properties in devtools console.
just select a component in dom tree and in console call the following code:
```
$state.param = newValue;
$apply();
```
